const CONFIG = {
    CANVAS_WIDTH: 1200,
    CANVAS_HEIGHT: 700,

    GRAVITY: 0.12,
    PROJECTILE_GRAVITY: 0.5,
    FRICTION: 0.92,

    PLAYER_SPEED: 2.5,
    PLAYER_JUMP: -5,
    PLAYER_WIDTH: 30,
    PLAYER_HEIGHT: 50,

    TERRAIN_HEIGHT_OFFSET: 200,
    TERRAIN_COLOR: '#5a3a1a',
    TERRAIN_DARK: '#3d2510',

    PROJECTILE_SPEED_MIN: 5,
    PROJECTILE_SPEED_MAX: 18,
    PROJECTILE_RADIUS: 5,
    DESTROY_RADIUS: 25,
    PARABOLA_STEPS: 40,
    PARABOLA_SPACING: 8,

    START_GOLD: 10000,

    WEAPONS: [
        {
            name: 'Cañón',
            damage: 35,
            range: 600,
            destroyRadius: 25,
            projectileRadius: 5,
            minSpeed: 7,
            maxSpeed: 18,
            gravity: 0.5,
            bounceCount: 0,
            guided: false,
            fireRate: 18,
            shots: 1,
            reloadTime: 30,
            infinite: true,
            color: '#ff6600',
        },
        {
            name: 'Cañón pesado',
            damage: 60,
            range: 550,
            destroyRadius: 32,
            projectileRadius: 7,
            minSpeed: 6,
            maxSpeed: 14,
            gravity: 0.7,
            bounceCount: 0,
            guided: false,
            fireRate: 30,
            shots: 1,
            reloadTime: 40,
            startStock: 8,
            packSize: 8,
            price: 40,
            color: '#ff3300',
        },
        {
            name: 'Antigravedad',
            damage: 12,
            range: 700,
            destroyRadius: 14,
            projectileRadius: 4,
            minSpeed: 5,
            maxSpeed: 15,
            gravity: 0.12,
            bounceCount: 0,
            guided: false,
            fireRate: 8,
            shots: 5,
            reloadTime: 60,
            startStock: 30,
            packSize: 20,
            price: 25,
            color: '#00c8ff',
        },
        {
            name: 'Granada',
            damage: 40,
            range: 450,
            destroyRadius: 30,
            projectileRadius: 6,
            minSpeed: 8,
            maxSpeed: 16,
            gravity: 0.5,
            bounceCount: 1,
            guided: false,
            fireRate: 40,
            shots: 1,
            reloadTime: 50,
            startStock: 10,
            packSize: 5,
            price: 50,
            color: '#66cc33',
        },
        {
            name: 'Misil guiado',
            damage: 70,
            range: 900,
            destroyRadius: 38,
            projectileRadius: 8,
            minSpeed: 4,
            maxSpeed: 9,
            gravity: 0.3,
            bounceCount: 0,
            guided: true,
            fireRate: 35,
            shots: 2,
            reloadTime: 60,
            startStock: 5,
            packSize: 5,
            price: 100,
            color: '#ff0000',
        },
    ],
};
