const CONFIG = {
    CANVAS_WIDTH: 1200,
    CANVAS_HEIGHT: 700,

    GRAVITY: 0.12,
    PROJECTILE_GRAVITY: 0.5,
    FRICTION: 0.92,

    PLAYER_SPEED: 2.5,
    PLAYER_JUMP: -5,
    PLAYER_WIDTH: 30,
    PLAYER_HEIGHT: 50,

    TERRAIN_HEIGHT_OFFSET: 200,
    TERRAIN_COLOR: '#5a3a1a',
    TERRAIN_DARK: '#3d2510',

    PROJECTILE_SPEED_MIN: 5,
    PROJECTILE_SPEED_MAX: 18,
    PROJECTILE_RADIUS: 5,
    DESTROY_RADIUS: 25,
    PARABOLA_STEPS: 40,
    PARABOLA_SPACING: 8,
    SKY_SPAWN_Y: -30,
    DROP_SPAWN_PADDING: 40,

    START_GOLD: 10000,

    WEAPONS: [
        {
            name: 'Cañón',
            damage: 35,
            range: 600,
            destroyRadius: 25,
            projectileRadius: 5,
            minSpeed: 7,
            maxSpeed: 18,
            gravity: 0.5,
            bounceCount: 0,
            guided: false,
            fireRate: 18,
            shots: 1,
            reloadTime: 30,
            infinite: true,
            icon: 'img/guns/default.png',
            projectileImage: 'img/projectile/default.png',
            color: '#ff6600',
        },
        {
            name: 'Cañón pesado',
            damage: 60,
            range: 550,
            destroyRadius: 32,
            projectileRadius: 7,
            minSpeed: 6,
            maxSpeed: 14,
            gravity: 0.7,
            bounceCount: 0,
            guided: false,
            fireRate: 30,
            shots: 1,
            reloadTime: 40,
            startStock: 8,
            packSize: 8,
            price: 40,
            icon: 'img/guns/canon.png',
            projectileImage: 'img/projectile/default.png',
            color: '#ff3300',
        },
        {
            name: 'Antigravedad',
            damage: 12,
            range: 700,
            destroyRadius: 14,
            projectileRadius: 4,
            minSpeed: 5,
            maxSpeed: 15,
            gravity: 0.12,
            bounceCount: 0,
            guided: false,
            fireRate: 8,
            shots: 5,
            reloadTime: 60,
            startStock: 30,
            packSize: 20,
            price: 25,
            icon: 'img/guns/antigravity.png',
            projectileImage: 'img/projectile/default.png',
            color: '#00c8ff',
        },
        {
            name: 'Granada',
            damage: 40,
            range: 450,
            destroyRadius: 30,
            projectileRadius: 6,
            minSpeed: 8,
            maxSpeed: 16,
            gravity: 0.5,
            bounceCount: 1,
            guided: false,
            fireRate: 40,
            shots: 1,
            reloadTime: 50,
            startStock: 10,
            packSize: 5,
            price: 50,
            icon: 'img/guns/f1.png',
            projectileImage: 'img/projectile/default.png',
            color: '#66cc33',
        },
        {
            name: 'Misil guiado',
            damage: 70,
            range: 900,
            destroyRadius: 38,
            projectileRadius: 8,
            minSpeed: 4,
            maxSpeed: 9,
            gravity: 0.3,
            bounceCount: 0,
            guided: true,
            fireRate: 35,
            shots: 2,
            reloadTime: 60,
            startStock: 5,
            packSize: 5,
            price: 100,
            icon: 'img/guns/guidedmissile.png',
            projectileImage: 'img/projectile/default.png',
            color: '#ff0000',
        },
        {
            name: 'Skybomb',
            damage: 90,
            range: 1000,
            destroyRadius: 45,
            projectileRadius: 9,
            minSpeed: 2,
            maxSpeed: 8,
            gravity: 0.5,
            bounceCount: 0,
            guided: false,
            spawnFrom: 'sky',
            fireRate: 50,
            shots: 1,
            reloadTime: 60,
            startStock: 4,
            packSize: 3,
            price: 80,
            icon: 'img/guns/default.png',
            projectileImage: 'img/projectile/default.png',
            color: '#a020f0',
        },
        {
            name: 'Shuriken',
            damage: 25,
            range: 500,
            destroyRadius: 20,
            projectileRadius: 6,
            minSpeed: 10,
            maxSpeed: 20,
            gravity: 0.15,
            bounceCount: 3,
            guided: false,
            breaksTerrain: false,
            maxLifetime: 150,
            fireRate: 12,
            shots: 3,
            reloadTime: 40,
            startStock: 12,
            packSize: 6,
            price: 30,
            icon: 'img/guns/default.png',
            projectileImage: 'img/projectile/default.png',
            color: '#c0c0c0',
        },
        {
            name: 'Multicañón',
            damage: 30,
            range: 550,
            destroyRadius: 22,
            projectileRadius: 5,
            minSpeed: 6,
            maxSpeed: 16,
            gravity: 0.5,
            bounceCount: 0,
            guided: false,
            projectileCount: 3,
            spreadAngle: 0.12,
            fireRate: 24,
            shots: 1,
            reloadTime: 40,
            startStock: 10,
            packSize: 5,
            price: 45,
            icon: 'img/guns/default.png',
            projectileImage: 'img/projectile/default.png',
            color: '#ff8c00',
        },
        {
            name: 'Drill',
            damage: 45,
            range: 400,
            destroyRadius: 14,
            projectileRadius: 8,
            minSpeed: 8,
            maxSpeed: 18,
            gravity: 0,
            bounceCount: 0,
            guided: false,
            drill: true,
            fireRate: 30,
            shots: 1,
            reloadTime: 50,
            startStock: 6,
            packSize: 4,
            price: 60,
            icon: 'img/guns/default.png',
            projectileImage: 'img/projectile/default.png',
            color: '#ffb300',
        },
        {
            name: 'Drop',
            damage: 0,
            range: 1000,
            destroyRadius: 0,
            projectileRadius: 12,
            minSpeed: 0,
            maxSpeed: 0,
            gravity: 0.05,
            bounceCount: 0,
            guided: false,
            spawnFrom: 'sky',
            drop: true,
            fallSpeed: 1.2,
            maxLifetime: 600,
            fireRate: 30,
            shots: 1,
            reloadTime: 40,
            startStock: 5,
            packSize: 1,
            price: 50,
            icon: 'img/guns/default.png',
            projectileImage: 'img/projectile/drop.png',
            color: '#ffd700',
        },
        {
            name: 'Inyección',
            damage: 0,
            range: 0,
            destroyRadius: 0,
            projectileRadius: 0,
            minSpeed: 0,
            maxSpeed: 0,
            gravity: 0,
            bounceCount: 0,
            guided: false,
            heal: 20,
            fireRate: 30,
            shots: 1,
            reloadTime: 35,
            startStock: 5,
            packSize: 3,
            price: 35,
            icon: 'img/guns/default.png',
            projectileImage: 'img/projectile/default.png',
            color: '#4caf50',
        },
    ],
};
